version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Linter (ESLint)
          command: npm run lint
      - run:
          name: Install formatter (prettier)
          command: npm install --save-dev prettier
      - run:
          name: Run prettier
          command: npx prettier --write .
      - run:
          name: Test Jest
          command: npm run test
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'stage' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'stage' ]; then
              aws s3 sync build s3://$CIRCLE_BRANCH-application-bucket-rdicidr --delete --exact-timestamps;
            fi
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - stage
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - stage